context:
  version: 1.1.2

package:
  name: fixjson
  version: ${{ version }}

source:
  url: https://registry.npmjs.org/fixjson/-/fixjson-${{ version }}.tgz
  sha256: 28bcae94ecfbe7495f778066216946fd1858c1ff612981f4f3d6fa12a884c879

build:
  number: 0
  noarch: generic

requirements:
  host:
    - nodejs
    - pnpm
    - pnpm-licenses
  run:
    - nodejs

tests:
  - script:
      - fixjson --help

about:
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: JSON Fixer for Humans using (relaxed) JSON5
  homepage: https://github.com/rhysd/fixjson
  repository: https://github.com/rhysd/fixjson

extra:
  recipe-maintainers:
    - danielnachun
